image: python:3.9

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install mkdocs mkdocs-material
    # Ensure the docs directory exists
    - mkdir -p docs
    # Copy all Markdown files and images into the docs directory
    - cp -r documentation/. docs/
    - cp README.md docs/
    # Build MkDocs site
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main
