stages:
  - build
  - pages

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache bash curl git
  script:
    - docker info
    - docker build -t lunchhunt:latest .
    - docker save lunchhunt:latest -o lunchhunt.tar
  artifacts:
    paths:
      - lunchhunt.tar
    expire_in: 1 week
  only:
    - develop
  tags:
    - docker

pages:
  stage: pages
  image: python:3.9
  script:
    - pip install mkdocs mkdocs-material
    - mkdir -p docs
    - cp -r img/. docs/img
    - cp -r documentation/notify/. docs/notify
    - cp -r documentation/scrap/. docs/scrap
    - cp -r documentation/examples/. docs/examples
    - cp README.md docs/
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main