site_name: LunchHunt Documentation
theme:
  name: material

nav:
  - Home: README.md
  - Scrap Module:
      - MensaScraper: scrap/scraper.md
  - Notify Module:
      - Notifier: notify.md
      - Notifier: notify/notifier.md

# Ensure images are served correctly
markdown_extensions:
  - attr_list
  - md_in_html
