site_name: LunchHunt Documentation
theme:
  name: material

nav:
  - Home: README.md
  - Scrap Module:
      - MensaScraper: scrap/scraper.md
  - Notify Module:
      - Notifier: notify/notifier.md
  - Example Usage:
      - Mensa Dishes Notification: examples/example_1.md
      - Favorite Foods Notification: examples/example_2.md

# Ensure images are served correctly
markdown_extensions:
  - attr_list
  - md_in_html
